name: Fly Deploy
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '30 20 1 * *'

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Check updates
        run: |
          # 从.env文件中读取当前版本号
          env_version=$(grep "^version=" .env | cut -d '=' -f 2)
          # 获取最新版本号
          latest_release=$(curl -s https://api.github.com/repos/naiba/nezha/releases/latest | grep "tag_name" | cut -d'"' -f4)
          # 处理版本号比较
          if [[ "$latest_release" == "$env_version" || -z "$latest_release" ]]; then
            echo "版本号一致/获取失败，无需更新"
            echo "new_release=no" >> $GITHUB_ENV
          else
            echo "新版本可用，正在更新..."
            echo "new_release=yes" >> $GITHUB_ENV
            sed -i "s/version=$env_version/version=$latest_release/g" .env
          fi

      - name: Deploy
        if: ${{ env.new_release == 'yes'  }}
        run: |
          echo '${{ secrets.CONFIG }}' > ./config.yaml && ls
          flyctl deploy --remote-only

      - name: Commit and push changes
        if: ${{ env.new_release == 'yes'  }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Version update

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1
